# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment: 
    SQS_URL: 'https://sqs.us-east-1.amazonaws.com/343875848202/catalogItemsQueue'

  stage: dev
  region: us-east-1

  httpApi:
    cors: true
    authorizers:
      basicAuthorizer:
        type: request
        functionArn: arn:aws:lambda:us-east-1:343875848202:function:authorization-service-dev-basicAuthorizer

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "arn:aws:s3:::zooshop-import/*"
        - Effect: "Allow"
          Action:
            - "sqs:*"
          Resource: "arn:aws:sqs:us-east-1:343875848202:catalogItemsQueue"

package:
    individually: true

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: ./handlers/importProductsFile.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          authorizer:
            name: basicAuthorizer
            

  importFileParser:
    handler: ./handlers/importFileParser.importFileParser

    events:
      - s3:
          bucket: zooshop-import
          event: s3:ObjectCreated:*
          rules: 
              - prefix: uploaded/
          existing: true
